// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tilawa.Api.Data;

#nullable disable

namespace Tilawa.Api.Data.Migrations
{
    [DbContext(typeof(TilawaDbContext))]
    [Migration("20260909133238_AddMasteryDecayTracking")]
    partial class AddMasteryDecayTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Tilawa.Api.Models.ActivityDay", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuranReadCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SurahNumbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "Date");

                    b.ToTable("ActivityDays");
                });

            modelBuilder.Entity("Tilawa.Api.Models.RecitationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("CoveredRefs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurahNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersesAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersesMatched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("RecitationSessions");
                });

            modelBuilder.Entity("Tilawa.Api.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Tilawa.Api.Models.RevisionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReminderTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SurahNumbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RevisionPlans");
                });

            modelBuilder.Entity("Tilawa.Api.Models.Surah", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AyahCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JuzLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Number");

                    b.ToTable("Surahs");

                    b.HasData(
                        new
                        {
                            Number = 1,
                            ArabicName = "سُورَةُ ٱلْفَاتِحَةِ",
                            AyahCount = 7,
                            EnglishName = "Al-Faatiha",
                            JuzLabel = "Juz 1"
                        },
                        new
                        {
                            Number = 2,
                            ArabicName = "سُورَةُ البَقَرَةِ",
                            AyahCount = 286,
                            EnglishName = "Al-Baqara",
                            JuzLabel = "Juz 1"
                        },
                        new
                        {
                            Number = 3,
                            ArabicName = "سُورَةُ آلِ عِمۡرَانَ",
                            AyahCount = 200,
                            EnglishName = "Aal-i-Imraan",
                            JuzLabel = "Juz 3"
                        },
                        new
                        {
                            Number = 4,
                            ArabicName = "سُورَةُ النِّسَاءِ",
                            AyahCount = 176,
                            EnglishName = "An-Nisaa",
                            JuzLabel = "Juz 4"
                        },
                        new
                        {
                            Number = 5,
                            ArabicName = "سُورَةُ المَائـِدَةِ",
                            AyahCount = 120,
                            EnglishName = "Al-Maaida",
                            JuzLabel = "Juz 6"
                        },
                        new
                        {
                            Number = 6,
                            ArabicName = "سُورَةُ الأَنۡعَامِ",
                            AyahCount = 165,
                            EnglishName = "Al-An'aam",
                            JuzLabel = "Juz 7"
                        },
                        new
                        {
                            Number = 7,
                            ArabicName = "سُورَةُ الأَعۡرَافِ",
                            AyahCount = 206,
                            EnglishName = "Al-A'raaf",
                            JuzLabel = "Juz 8"
                        },
                        new
                        {
                            Number = 8,
                            ArabicName = "سُورَةُ الأَنفَالِ",
                            AyahCount = 75,
                            EnglishName = "Al-Anfaal",
                            JuzLabel = "Juz 9"
                        },
                        new
                        {
                            Number = 9,
                            ArabicName = "سُورَةُ التَّوۡبَةِ",
                            AyahCount = 129,
                            EnglishName = "At-Tawba",
                            JuzLabel = "Juz 10"
                        },
                        new
                        {
                            Number = 10,
                            ArabicName = "سُورَةُ يُونُسَ",
                            AyahCount = 109,
                            EnglishName = "Yunus",
                            JuzLabel = "Juz 11"
                        },
                        new
                        {
                            Number = 11,
                            ArabicName = "سُورَةُ هُودٍ",
                            AyahCount = 123,
                            EnglishName = "Hud",
                            JuzLabel = "Juz 11"
                        },
                        new
                        {
                            Number = 12,
                            ArabicName = "سُورَةُ يُوسُفَ",
                            AyahCount = 111,
                            EnglishName = "Yusuf",
                            JuzLabel = "Juz 12"
                        },
                        new
                        {
                            Number = 13,
                            ArabicName = "سُورَةُ الرَّعۡدِ",
                            AyahCount = 43,
                            EnglishName = "Ar-Ra'd",
                            JuzLabel = "Juz 13"
                        },
                        new
                        {
                            Number = 14,
                            ArabicName = "سُورَةُ إِبۡرَاهِيمَ",
                            AyahCount = 52,
                            EnglishName = "Ibrahim",
                            JuzLabel = "Juz 13"
                        },
                        new
                        {
                            Number = 15,
                            ArabicName = "سُورَةُ الحِجۡرِ",
                            AyahCount = 99,
                            EnglishName = "Al-Hijr",
                            JuzLabel = "Juz 14"
                        },
                        new
                        {
                            Number = 16,
                            ArabicName = "سُورَةُ النَّحۡلِ",
                            AyahCount = 128,
                            EnglishName = "An-Nahl",
                            JuzLabel = "Juz 14"
                        },
                        new
                        {
                            Number = 17,
                            ArabicName = "سُورَةُ الإِسۡرَاءِ",
                            AyahCount = 111,
                            EnglishName = "Al-Israa",
                            JuzLabel = "Juz 15"
                        },
                        new
                        {
                            Number = 18,
                            ArabicName = "سُورَةُ الكَهۡفِ",
                            AyahCount = 110,
                            EnglishName = "Al-Kahf",
                            JuzLabel = "Juz 15"
                        },
                        new
                        {
                            Number = 19,
                            ArabicName = "سُورَةُ مَرۡيَمَ",
                            AyahCount = 98,
                            EnglishName = "Maryam",
                            JuzLabel = "Juz 16"
                        },
                        new
                        {
                            Number = 20,
                            ArabicName = "سُورَةُ طه",
                            AyahCount = 135,
                            EnglishName = "Taa-Haa",
                            JuzLabel = "Juz 16"
                        },
                        new
                        {
                            Number = 21,
                            ArabicName = "سُورَةُ الأَنبِيَاءِ",
                            AyahCount = 112,
                            EnglishName = "Al-Anbiyaa",
                            JuzLabel = "Juz 17"
                        },
                        new
                        {
                            Number = 22,
                            ArabicName = "سُورَةُ الحَجِّ",
                            AyahCount = 78,
                            EnglishName = "Al-Hajj",
                            JuzLabel = "Juz 17"
                        },
                        new
                        {
                            Number = 23,
                            ArabicName = "سُورَةُ المُؤۡمِنُونَ",
                            AyahCount = 118,
                            EnglishName = "Al-Muminoon",
                            JuzLabel = "Juz 18"
                        },
                        new
                        {
                            Number = 24,
                            ArabicName = "سُورَةُ النُّورِ",
                            AyahCount = 64,
                            EnglishName = "An-Noor",
                            JuzLabel = "Juz 18"
                        },
                        new
                        {
                            Number = 25,
                            ArabicName = "سُورَةُ الفُرۡقَانِ",
                            AyahCount = 77,
                            EnglishName = "Al-Furqaan",
                            JuzLabel = "Juz 18"
                        },
                        new
                        {
                            Number = 26,
                            ArabicName = "سُورَةُ الشُّعَرَاءِ",
                            AyahCount = 227,
                            EnglishName = "Ash-Shu'araa",
                            JuzLabel = "Juz 19"
                        },
                        new
                        {
                            Number = 27,
                            ArabicName = "سُورَةُ النَّمۡلِ",
                            AyahCount = 93,
                            EnglishName = "An-Naml",
                            JuzLabel = "Juz 19"
                        },
                        new
                        {
                            Number = 28,
                            ArabicName = "سُورَةُ القَصَصِ",
                            AyahCount = 88,
                            EnglishName = "Al-Qasas",
                            JuzLabel = "Juz 20"
                        },
                        new
                        {
                            Number = 29,
                            ArabicName = "سُورَةُ العَنكَبُوتِ",
                            AyahCount = 69,
                            EnglishName = "Al-Ankaboot",
                            JuzLabel = "Juz 20"
                        },
                        new
                        {
                            Number = 30,
                            ArabicName = "سُورَةُ الرُّومِ",
                            AyahCount = 60,
                            EnglishName = "Ar-Room",
                            JuzLabel = "Juz 21"
                        },
                        new
                        {
                            Number = 31,
                            ArabicName = "سُورَةُ لُقۡمَانَ",
                            AyahCount = 34,
                            EnglishName = "Luqman",
                            JuzLabel = "Juz 21"
                        },
                        new
                        {
                            Number = 32,
                            ArabicName = "سُورَةُ السَّجۡدَةِ",
                            AyahCount = 30,
                            EnglishName = "As-Sajda",
                            JuzLabel = "Juz 21"
                        },
                        new
                        {
                            Number = 33,
                            ArabicName = "سُورَةُ الأَحۡزَابِ",
                            AyahCount = 73,
                            EnglishName = "Al-Ahzaab",
                            JuzLabel = "Juz 21"
                        },
                        new
                        {
                            Number = 34,
                            ArabicName = "سُورَةُ سَبَإٍ",
                            AyahCount = 54,
                            EnglishName = "Saba",
                            JuzLabel = "Juz 22"
                        },
                        new
                        {
                            Number = 35,
                            ArabicName = "سُورَةُ فَاطِرٍ",
                            AyahCount = 45,
                            EnglishName = "Faatir",
                            JuzLabel = "Juz 22"
                        },
                        new
                        {
                            Number = 36,
                            ArabicName = "سُورَةُ يسٓ",
                            AyahCount = 83,
                            EnglishName = "Yaseen",
                            JuzLabel = "Juz 22"
                        },
                        new
                        {
                            Number = 37,
                            ArabicName = "سُورَةُ الصَّافَّاتِ",
                            AyahCount = 182,
                            EnglishName = "As-Saaffaat",
                            JuzLabel = "Juz 23"
                        },
                        new
                        {
                            Number = 38,
                            ArabicName = "سُورَةُ صٓ",
                            AyahCount = 88,
                            EnglishName = "Saad",
                            JuzLabel = "Juz 23"
                        },
                        new
                        {
                            Number = 39,
                            ArabicName = "سُورَةُ الزُّمَرِ",
                            AyahCount = 75,
                            EnglishName = "Az-Zumar",
                            JuzLabel = "Juz 23"
                        },
                        new
                        {
                            Number = 40,
                            ArabicName = "سُورَةُ غَافِرٍ",
                            AyahCount = 85,
                            EnglishName = "Ghafir",
                            JuzLabel = "Juz 24"
                        },
                        new
                        {
                            Number = 41,
                            ArabicName = "سُورَةُ فُصِّلَتۡ",
                            AyahCount = 54,
                            EnglishName = "Fussilat",
                            JuzLabel = "Juz 24"
                        },
                        new
                        {
                            Number = 42,
                            ArabicName = "سُورَةُ الشُّورَىٰ",
                            AyahCount = 53,
                            EnglishName = "Ash-Shura",
                            JuzLabel = "Juz 25"
                        },
                        new
                        {
                            Number = 43,
                            ArabicName = "سُورَةُ الزُّخۡرُفِ",
                            AyahCount = 89,
                            EnglishName = "Az-Zukhruf",
                            JuzLabel = "Juz 25"
                        },
                        new
                        {
                            Number = 44,
                            ArabicName = "سُورَةُ الدُّخَانِ",
                            AyahCount = 59,
                            EnglishName = "Ad-Dukhaan",
                            JuzLabel = "Juz 25"
                        },
                        new
                        {
                            Number = 45,
                            ArabicName = "سُورَةُ الجَاثِيَةِ",
                            AyahCount = 37,
                            EnglishName = "Al-Jaathiya",
                            JuzLabel = "Juz 25"
                        },
                        new
                        {
                            Number = 46,
                            ArabicName = "سُورَةُ الأَحۡقَافِ",
                            AyahCount = 35,
                            EnglishName = "Al-Ahqaf",
                            JuzLabel = "Juz 26"
                        },
                        new
                        {
                            Number = 47,
                            ArabicName = "سُورَةُ مُحَمَّدٍ",
                            AyahCount = 38,
                            EnglishName = "Muhammad",
                            JuzLabel = "Juz 26"
                        },
                        new
                        {
                            Number = 48,
                            ArabicName = "سُورَةُ الفَتۡحِ",
                            AyahCount = 29,
                            EnglishName = "Al-Fath",
                            JuzLabel = "Juz 26"
                        },
                        new
                        {
                            Number = 49,
                            ArabicName = "سُورَةُ الحُجُرَاتِ",
                            AyahCount = 18,
                            EnglishName = "Al-Hujuraat",
                            JuzLabel = "Juz 26"
                        },
                        new
                        {
                            Number = 50,
                            ArabicName = "سُورَةُ قٓ",
                            AyahCount = 45,
                            EnglishName = "Qaaf",
                            JuzLabel = "Juz 26"
                        },
                        new
                        {
                            Number = 51,
                            ArabicName = "سُورَةُ الذَّارِيَاتِ",
                            AyahCount = 60,
                            EnglishName = "Adh-Dhaariyat",
                            JuzLabel = "Juz 26"
                        },
                        new
                        {
                            Number = 52,
                            ArabicName = "سُورَةُ الطُّورِ",
                            AyahCount = 49,
                            EnglishName = "At-Tur",
                            JuzLabel = "Juz 27"
                        },
                        new
                        {
                            Number = 53,
                            ArabicName = "سُورَةُ النَّجۡمِ",
                            AyahCount = 62,
                            EnglishName = "An-Najm",
                            JuzLabel = "Juz 27"
                        },
                        new
                        {
                            Number = 54,
                            ArabicName = "سُورَةُ القَمَرِ",
                            AyahCount = 55,
                            EnglishName = "Al-Qamar",
                            JuzLabel = "Juz 27"
                        },
                        new
                        {
                            Number = 55,
                            ArabicName = "سُورَةُ الرَّحۡمَٰن",
                            AyahCount = 78,
                            EnglishName = "Ar-Rahmaan",
                            JuzLabel = "Juz 27"
                        },
                        new
                        {
                            Number = 56,
                            ArabicName = "سُورَةُ الوَاقِعَةِ",
                            AyahCount = 96,
                            EnglishName = "Al-Waaqia",
                            JuzLabel = "Juz 27"
                        },
                        new
                        {
                            Number = 57,
                            ArabicName = "سُورَةُ الحَدِيدِ",
                            AyahCount = 29,
                            EnglishName = "Al-Hadid",
                            JuzLabel = "Juz 27"
                        },
                        new
                        {
                            Number = 58,
                            ArabicName = "سُورَةُ المُجَادلَةِ",
                            AyahCount = 22,
                            EnglishName = "Al-Mujaadila",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 59,
                            ArabicName = "سُورَةُ الحَشۡرِ",
                            AyahCount = 24,
                            EnglishName = "Al-Hashr",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 60,
                            ArabicName = "سُورَةُ المُمۡتَحنَةِ",
                            AyahCount = 13,
                            EnglishName = "Al-Mumtahana",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 61,
                            ArabicName = "سُورَةُ الصَّفِّ",
                            AyahCount = 14,
                            EnglishName = "As-Saff",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 62,
                            ArabicName = "سُورَةُ الجُمُعَةِ",
                            AyahCount = 11,
                            EnglishName = "Al-Jumu'a",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 63,
                            ArabicName = "سُورَةُ المُنَافِقُونَ",
                            AyahCount = 11,
                            EnglishName = "Al-Munaafiqoon",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 64,
                            ArabicName = "سُورَةُ التَّغَابُنِ",
                            AyahCount = 18,
                            EnglishName = "At-Taghaabun",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 65,
                            ArabicName = "سُورَةُ الطَّلَاقِ",
                            AyahCount = 12,
                            EnglishName = "At-Talaaq",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 66,
                            ArabicName = "سُورَةُ التَّحۡرِيمِ",
                            AyahCount = 12,
                            EnglishName = "At-Tahrim",
                            JuzLabel = "Juz 28"
                        },
                        new
                        {
                            Number = 67,
                            ArabicName = "سُورَةُ المُلۡكِ",
                            AyahCount = 30,
                            EnglishName = "Al-Mulk",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 68,
                            ArabicName = "سُورَةُ القَلَمِ",
                            AyahCount = 52,
                            EnglishName = "Al-Qalam",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 69,
                            ArabicName = "سُورَةُ الحَاقَّةِ",
                            AyahCount = 52,
                            EnglishName = "Al-Haaqqa",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 70,
                            ArabicName = "سُورَةُ المَعَارِجِ",
                            AyahCount = 44,
                            EnglishName = "Al-Ma'aarij",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 71,
                            ArabicName = "سُورَةُ نُوحٍ",
                            AyahCount = 28,
                            EnglishName = "Nooh",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 72,
                            ArabicName = "سُورَةُ الجِنِّ",
                            AyahCount = 28,
                            EnglishName = "Al-Jinn",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 73,
                            ArabicName = "سُورَةُ المُزَّمِّلِ",
                            AyahCount = 20,
                            EnglishName = "Al-Muzzammil",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 74,
                            ArabicName = "سُورَةُ المُدَّثِّرِ",
                            AyahCount = 56,
                            EnglishName = "Al-Muddaththir",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 75,
                            ArabicName = "سُورَةُ القِيَامَةِ",
                            AyahCount = 40,
                            EnglishName = "Al-Qiyaama",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 76,
                            ArabicName = "سُورَةُ الإِنسَانِ",
                            AyahCount = 31,
                            EnglishName = "Al-Insaan",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 77,
                            ArabicName = "سُورَةُ المُرۡسَلَاتِ",
                            AyahCount = 50,
                            EnglishName = "Al-Mursalaat",
                            JuzLabel = "Juz Tabarak"
                        },
                        new
                        {
                            Number = 78,
                            ArabicName = "سُورَةُ النَّبَإِ",
                            AyahCount = 40,
                            EnglishName = "An-Naba",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 79,
                            ArabicName = "سُورَةُ النَّازِعَاتِ",
                            AyahCount = 46,
                            EnglishName = "An-Naazi'aat",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 80,
                            ArabicName = "سُورَةُ عَبَسَ",
                            AyahCount = 42,
                            EnglishName = "Abasa",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 81,
                            ArabicName = "سُورَةُ التَّكۡوِيرِ",
                            AyahCount = 29,
                            EnglishName = "At-Takwir",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 82,
                            ArabicName = "سُورَةُ الانفِطَارِ",
                            AyahCount = 19,
                            EnglishName = "Al-Infitaar",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 83,
                            ArabicName = "سُورَةُ المُطَفِّفِينَ",
                            AyahCount = 36,
                            EnglishName = "Al-Mutaffifin",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 84,
                            ArabicName = "سُورَةُ الانشِقَاقِ",
                            AyahCount = 25,
                            EnglishName = "Al-Inshiqaaq",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 85,
                            ArabicName = "سُورَةُ البُرُوجِ",
                            AyahCount = 22,
                            EnglishName = "Al-Burooj",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 86,
                            ArabicName = "سُورَةُ الطَّارِقِ",
                            AyahCount = 17,
                            EnglishName = "At-Taariq",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 87,
                            ArabicName = "سُورَةُ الأَعۡلَىٰ",
                            AyahCount = 19,
                            EnglishName = "Al-A'laa",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 88,
                            ArabicName = "سُورَةُ الغَاشِيَةِ",
                            AyahCount = 26,
                            EnglishName = "Al-Ghaashiya",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 89,
                            ArabicName = "سُورَةُ الفَجۡرِ",
                            AyahCount = 30,
                            EnglishName = "Al-Fajr",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 90,
                            ArabicName = "سُورَةُ البَلَدِ",
                            AyahCount = 20,
                            EnglishName = "Al-Balad",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 91,
                            ArabicName = "سُورَةُ الشَّمۡسِ",
                            AyahCount = 15,
                            EnglishName = "Ash-Shams",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 92,
                            ArabicName = "سُورَةُ اللَّيۡلِ",
                            AyahCount = 21,
                            EnglishName = "Al-Lail",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 93,
                            ArabicName = "سُورَةُ الضُّحَىٰ",
                            AyahCount = 11,
                            EnglishName = "Ad-Dhuhaa",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 94,
                            ArabicName = "سُورَةُ الشَّرۡحِ",
                            AyahCount = 8,
                            EnglishName = "Ash-Sharh",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 95,
                            ArabicName = "سُورَةُ التِّينِ",
                            AyahCount = 8,
                            EnglishName = "At-Tin",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 96,
                            ArabicName = "سُورَةُ العَلَقِ",
                            AyahCount = 19,
                            EnglishName = "Al-Alaq",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 97,
                            ArabicName = "سُورَةُ القَدۡرِ",
                            AyahCount = 5,
                            EnglishName = "Al-Qadr",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 98,
                            ArabicName = "سُورَةُ البَيِّنَةِ",
                            AyahCount = 8,
                            EnglishName = "Al-Bayyina",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 99,
                            ArabicName = "سُورَةُ الزَّلۡزَلَةِ",
                            AyahCount = 8,
                            EnglishName = "Az-Zalzala",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 100,
                            ArabicName = "سُورَةُ العَادِيَاتِ",
                            AyahCount = 11,
                            EnglishName = "Al-Aadiyaat",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 101,
                            ArabicName = "سُورَةُ القَارِعَةِ",
                            AyahCount = 11,
                            EnglishName = "Al-Qaari'a",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 102,
                            ArabicName = "سُورَةُ التَّكَاثُرِ",
                            AyahCount = 8,
                            EnglishName = "At-Takaathur",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 103,
                            ArabicName = "سُورَةُ العَصۡرِ",
                            AyahCount = 3,
                            EnglishName = "Al-Asr",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 104,
                            ArabicName = "سُورَةُ الهُمَزَةِ",
                            AyahCount = 9,
                            EnglishName = "Al-Humaza",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 105,
                            ArabicName = "سُورَةُ الفِيلِ",
                            AyahCount = 5,
                            EnglishName = "Al-Fil",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 106,
                            ArabicName = "سُورَةُ قُرَيۡشٍ",
                            AyahCount = 4,
                            EnglishName = "Quraish",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 107,
                            ArabicName = "سُورَةُ المَاعُونِ",
                            AyahCount = 7,
                            EnglishName = "Al-Maa'un",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 108,
                            ArabicName = "سُورَةُ الكَوۡثَرِ",
                            AyahCount = 3,
                            EnglishName = "Al-Kawthar",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 109,
                            ArabicName = "سُورَةُ الكَافِرُونَ",
                            AyahCount = 6,
                            EnglishName = "Al-Kaafiroon",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 110,
                            ArabicName = "سُورَةُ النَّصۡرِ",
                            AyahCount = 3,
                            EnglishName = "An-Nasr",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 111,
                            ArabicName = "سُورَةُ المَسَدِ",
                            AyahCount = 5,
                            EnglishName = "Al-Masad",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 112,
                            ArabicName = "سُورَةُ الإِخۡلَاصِ",
                            AyahCount = 4,
                            EnglishName = "Al-Ikhlaas",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 113,
                            ArabicName = "سُورَةُ الفَلَقِ",
                            AyahCount = 5,
                            EnglishName = "Al-Falaq",
                            JuzLabel = "Juz Amma"
                        },
                        new
                        {
                            Number = 114,
                            ArabicName = "سُورَةُ النَّاسِ",
                            AyahCount = 6,
                            EnglishName = "An-Naas",
                            JuzLabel = "Juz Amma"
                        });
                });

            modelBuilder.Entity("Tilawa.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSignedInAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tilawa.Api.Models.UserSurahProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SurahNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveGoodReviews")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastReviewed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastRevisionDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastRevisionSection")
                        .HasColumnType("TEXT");

                    b.Property<double>("Mastery")
                        .HasColumnType("REAL");

                    b.Property<double>("MistakeRate")
                        .HasColumnType("REAL");

                    b.Property<int>("QuranReadCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevisionIntensity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "SurahNumber");

                    b.HasIndex("SurahNumber");

                    b.ToTable("UserSurahProgress");
                });

            modelBuilder.Entity("Tilawa.Api.Models.ActivityDay", b =>
                {
                    b.HasOne("Tilawa.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tilawa.Api.Models.RecitationSession", b =>
                {
                    b.HasOne("Tilawa.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tilawa.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("Tilawa.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tilawa.Api.Models.RevisionPlan", b =>
                {
                    b.HasOne("Tilawa.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tilawa.Api.Models.UserSurahProgress", b =>
                {
                    b.HasOne("Tilawa.Api.Models.Surah", null)
                        .WithMany()
                        .HasForeignKey("SurahNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tilawa.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
