import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import 'package:tilawa/features/recitation/engine/arabic_normalizer.dart';
import 'package:tilawa/features/recitation/engine/ctc_decoder.dart';
import 'package:tilawa/features/recitation/engine/quran_db.dart';
import 'package:tilawa/features/recitation/engine/recitation_types.dart';

/// Asset paths for the bundled offline corpus.
class CorpusAssets {
  const CorpusAssets._();

  static const String verses = 'assets/quran/quran.json';
  static const String ctcTokens = 'assets/quran/quran_ctc_tokens.json';
  static const String vocab = 'assets/quran/vocab.json';
  static const String metadata = 'assets/quran/export_metadata.json';

  /// Optional: surah/ayah -> page, juz, hizb. Generated by
  /// `tools/build_quran_index.py`; the Mushaf reader falls back to online
  /// lookup when it is absent.
  static const String pageIndex = 'assets/quran/quran_index.json';
}

/// Static metadata for one surah.
class SurahInfo {
  const SurahInfo({
    required this.number,
    required this.arabicName,
    required this.englishName,
    required this.ayahCount,
    required this.startPage,
  });

  final int number;
  final String arabicName;
  final String englishName;
  final int ayahCount;
  final int startPage;
}

/// Where a verse sits in the printed Mushaf.
class AyahLocation {
  const AyahLocation({
    required this.surah,
    required this.ayah,
    required this.page,
    required this.juz,
    required this.hizbQuarter,
  });

  final int surah;
  final int ayah;
  final int page;
  final int juz;
  final int hizbQuarter;
}

/// The offline Quran corpus: verse text, precomputed CTC token ids, the
/// matcher index and (when the index asset is present) Mushaf page positions.
///
/// Loading is a one-off cost of a few hundred milliseconds; hold a single
/// instance for the life of the app.
class QuranCorpus {
  QuranCorpus._({
    required this.db,
    required this.decoder,
    required this.blankId,
    required this.modelSha256,
    required List<SurahInfo> surahs,
    required Map<String, AyahLocation> locations,
  })  : _surahs = surahs,
        _locations = locations;

  final QuranDB db;
  final CtcDecoder decoder;
  final int blankId;

  /// Expected SHA-256 of the ONNX model, from `export_metadata.json`.
  final String modelSha256;

  final List<SurahInfo> _surahs;
  final Map<String, AyahLocation> _locations;

  List<SurahInfo> get surahs => List.unmodifiable(_surahs);

  bool get hasPageIndex => _locations.isNotEmpty;

  SurahInfo? surahInfo(int surah) {
    for (final info in _surahs) {
      if (info.number == surah) return info;
    }
    return null;
  }

  AyahLocation? locate(int surah, int ayah) => _locations['$surah:$ayah'];

  /// Verses printed on one Mushaf page, in order. Empty when no page index is
  /// bundled.
  List<QuranVerse> versesOnPage(int page) {
    final result = <QuranVerse>[];
    for (final entry in _locations.values) {
      if (entry.page != page) continue;
      final verse = db.getVerse(entry.surah, entry.ayah);
      if (verse != null) result.add(verse);
    }
    result.sort((a, b) {
      final bySurah = a.surah.compareTo(b.surah);
      return bySurah != 0 ? bySurah : a.ayah.compareTo(b.ayah);
    });
    return result;
  }

  static Future<QuranCorpus> load() async {
    final metadata = jsonDecode(
      await rootBundle.loadString(CorpusAssets.metadata),
    ) as Map<String, dynamic>;

    final vocabJson = jsonDecode(
      await rootBundle.loadString(CorpusAssets.vocab),
    ) as Map<String, dynamic>;

    final blankId = (metadata['blank_id'] as num?)?.toInt() ?? 1024;
    final decoder = CtcDecoder(vocabJson, blankId: blankId);

    final ctcTokensRaw = jsonDecode(
      await rootBundle.loadString(CorpusAssets.ctcTokens),
    ) as Map<String, dynamic>;
    final ctcTokens = <String, List<int>>{
      for (final entry in ctcTokensRaw.entries)
        entry.key: (entry.value as List).cast<num>().map((n) => n.toInt()).toList(),
    };

    final versesRaw = jsonDecode(
      await rootBundle.loadString(CorpusAssets.verses),
    ) as List<dynamic>;

    final verses = <QuranVerse>[];
    for (final raw in versesRaw.cast<Map<String, dynamic>>()) {
      verses.add(_adaptVerse(raw, ctcTokens, decoder));
    }

    final surahs = _buildSurahIndex(verses);
    final locations = await _loadPageIndex();
    if (locations.isNotEmpty) {
      _applyStartPages(surahs, locations);
    }

    return QuranCorpus._(
      db: QuranDB(verses, ctcTokenTable: ctcTokens),
      decoder: decoder,
      blankId: blankId,
      modelSha256: (metadata['onnx_sha256'] as String?) ?? '',
      surahs: surahs,
      locations: locations,
    );
  }

  /// Turns a raw corpus row into a matcher-ready verse.
  ///
  /// The comparison text comes from decoding the verse's own precomputed CTC
  /// token ids, so a verse string and a decoded transcript are produced by the
  /// same tokenizer and are directly comparable. Verses with no token entry
  /// fall back to the normalized clean text.
  static QuranVerse _adaptVerse(
    Map<String, dynamic> raw,
    Map<String, List<int>> ctcTokens,
    CtcDecoder decoder,
  ) {
    final surah = (raw['surah'] as num).toInt();
    final ayah = (raw['ayah'] as num).toInt();
    final textUthmani = raw['text_uthmani'] as String;
    final clean = normalizeArabic((raw['text_clean'] as String?) ?? textUthmani);

    final tokenIds = ctcTokens['$surah:$ayah:$ayah'] ?? const <int>[];
    final decoded = decoder.tokenIdsToText(tokenIds);
    final joined = decoded.isNotEmpty ? decoded : clean;

    return QuranVerse(
      surah: surah,
      ayah: ayah,
      textUthmani: textUthmani,
      textClean: clean,
      surahName: (raw['surah_name'] as String?) ?? '',
      surahNameEn: (raw['surah_name_en'] as String?) ?? '',
      phonemesJoined: joined,
      phonemeTokens: decoder.tokenIdsToRawTokens(tokenIds),
      phonemeTokenIds: tokenIds,
      wordTokenEnds: decoder.tokenIdsToWordEnds(tokenIds),
      phonemeWords: splitWords(joined),
    );
  }

  static List<SurahInfo> _buildSurahIndex(List<QuranVerse> verses) {
    final counts = <int, int>{};
    final names = <int, ({String ar, String en})>{};
    for (final verse in verses) {
      counts[verse.surah] = (counts[verse.surah] ?? 0) + 1;
      names[verse.surah] ??= (ar: verse.surahName, en: verse.surahNameEn);
    }
    final numbers = counts.keys.toList()..sort();
    return [
      for (final number in numbers)
        SurahInfo(
          number: number,
          arabicName: names[number]!.ar,
          englishName: names[number]!.en,
          ayahCount: counts[number]!,
          startPage: 0,
        ),
    ];
  }

  static void _applyStartPages(
    List<SurahInfo> surahs,
    Map<String, AyahLocation> locations,
  ) {
    for (var i = 0; i < surahs.length; i++) {
      final first = locations['${surahs[i].number}:1'];
      if (first == null) continue;
      surahs[i] = SurahInfo(
        number: surahs[i].number,
        arabicName: surahs[i].arabicName,
        englishName: surahs[i].englishName,
        ayahCount: surahs[i].ayahCount,
        startPage: first.page,
      );
    }
  }

  static Future<Map<String, AyahLocation>> _loadPageIndex() async {
    final String source;
    try {
      source = await rootBundle.loadString(CorpusAssets.pageIndex);
    } catch (_) {
      // Optional asset, and rootBundle reports a missing one with a
      // FlutterError, so the catch has to be broad.
      return const {};
    }

    final decoded = jsonDecode(source);
    final rows = decoded is Map<String, dynamic>
        ? (decoded['ayahs'] as List<dynamic>)
        : decoded as List<dynamic>;

    final locations = <String, AyahLocation>{};
    for (final row in rows.cast<Map<String, dynamic>>()) {
      final surah = (row['surah'] as num).toInt();
      final ayah = (row['ayah'] as num).toInt();
      locations['$surah:$ayah'] = AyahLocation(
        surah: surah,
        ayah: ayah,
        page: (row['page'] as num).toInt(),
        juz: (row['juz'] as num?)?.toInt() ?? 1,
        hizbQuarter: (row['hizbQuarter'] as num?)?.toInt() ?? 1,
      );
    }
    return locations;
  }
}
