#!/usr/bin/env python3
"""Generate the celebration chimes.

Deliberately not music. A Quran app celebrating with a melody would be
inappropriate for a good share of the people using it, and the disagreement
about music is not one an app should settle on its users' behalf. What these
are instead is a struck tone — the sound of a small bell or a glass — which
carries a sense of occasion without being a tune: no melody, no rhythm, no
instruments, a single pitch per event.

They are synthesised here rather than downloaded so their provenance is beyond
question and so the five tiers are related by construction: the same bell, rung
higher and held longer as the occasion grows.

A struck tone is a fundamental plus *inharmonic* partials — ratios that are not
whole numbers, which is what distinguishes a bell from an organ — each decaying
at its own rate, with the high partials dying first.

Outputs to app/assets/sounds/. Run after changing any parameter here.

Usage:
    python tools/build_celebration_sounds.py
"""

from __future__ import annotations

import math
import struct
import wave
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "app" / "assets" / "sounds"

SAMPLE_RATE = 44_100

# Partial ratios of a struck bell, with how long each lasts relative to the
# fundamental. Non-integer on purpose: integer ratios sound like an instrument
# playing a note, which is what we are avoiding.
PARTIALS = [
    (1.00, 1.00, 1.00),  # ratio, amplitude, decay scale
    (2.76, 0.55, 0.62),
    (5.40, 0.30, 0.38),
    (8.93, 0.16, 0.24),
]

# One per celebration tier: the daily streak through to completing the Mushaf.
# Pitch rises and the tail lengthens, so the escalation is heard rather than
# merely counted.
TIERS = {
    "streak": (523.25, 0.9, 1),
    "quarter": (587.33, 1.3, 2),
    "half": (659.25, 1.7, 2),
    "three_quarters": (698.46, 2.1, 3),
    "whole": (783.99, 3.2, 4),
}

# Gap between strikes when a tier rings more than once.
STRIKE_GAP_SECONDS = 0.28


def bell(frequency: float, duration: float, strikes: int) -> list[float]:
    total = int(SAMPLE_RATE * (duration + STRIKE_GAP_SECONDS * (strikes - 1)))
    samples = [0.0] * total

    for strike in range(strikes):
        offset = int(SAMPLE_RATE * STRIKE_GAP_SECONDS * strike)
        # Later strikes sit slightly back, so the first one leads.
        gain = 1.0 if strike == 0 else 0.7

        for ratio, amplitude, decay_scale in PARTIALS:
            omega = 2 * math.pi * frequency * ratio
            decay = 3.2 / (duration * decay_scale)
            for n in range(total - offset):
                t = n / SAMPLE_RATE
                envelope = math.exp(-decay * t)
                if envelope < 1e-4:
                    break
                samples[offset + n] += gain * amplitude * envelope * math.sin(omega * t)

    # A couple of milliseconds of fade-in removes the click a hard start makes.
    attack = int(SAMPLE_RATE * 0.004)
    for n in range(min(attack, total)):
        samples[n] *= n / attack

    peak = max((abs(s) for s in samples), default=1.0) or 1.0
    return [s / peak * 0.82 for s in samples]


def write_wav(path: Path, samples: list[float]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(SAMPLE_RATE)
        handle.writeframes(
            b"".join(
                struct.pack("<h", max(-32768, min(32767, int(s * 32767))))
                for s in samples
            )
        )


def main() -> None:
    for name, (frequency, duration, strikes) in TIERS.items():
        samples = bell(frequency, duration, strikes)
        path = OUT_DIR / f"{name}.wav"
        write_wav(path, samples)
        print(f"{path.relative_to(REPO_ROOT)}  {len(samples) / SAMPLE_RATE:.2f}s  "
              f"{path.stat().st_size / 1024:.0f} KB")

    (OUT_DIR / "README.md").write_text(
        "# Celebration sounds\n\n"
        "Generated by `tools/build_celebration_sounds.py`. Do not replace these\n"
        "by hand — change the generator and re-run it.\n\n"
        "They are synthesised struck tones, not music: a single pitch per event\n"
        "with inharmonic partials, no melody and no instruments. This is a\n"
        "deliberate choice for a Quran app, and it also means the audio is\n"
        "wholly original with no licence to track.\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
