#!/usr/bin/env python3
"""Generate backend/Tilawa.Api/Data/SurahCatalog.cs from the bundled corpus.

The app and the API must agree on surah names, ayah counts and juz labels, so
both are derived from the same source of truth: the offline corpus the
recogniser uses (app/assets/quran/quran.json) plus the imported position index
(quran_index.json). Nothing here is hand-typed or invented.

Usage:
    python tools/build_surah_catalog.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CORPUS = REPO_ROOT / "app" / "assets" / "quran" / "quran.json"
INDEX = REPO_ROOT / "app" / "assets" / "quran" / "quran_index.json"
OUTPUT = REPO_ROOT / "backend" / "Tilawa.Api" / "Data" / "SurahCatalog.cs"

# The last two ajza' are universally known by name rather than number.
NAMED_JUZ = {29: "Juz Tabarak", 30: "Juz Amma"}


def load_surahs() -> list[dict]:
    corpus = json.loads(CORPUS.read_text(encoding="utf-8"))
    index = json.loads(INDEX.read_text(encoding="utf-8"))

    juz_of_first_ayah = {
        row["surah"]: row["juz"] for row in index["ayahs"] if row["ayah"] == 1
    }

    surahs: dict[int, dict] = {}
    for verse in corpus:
        number = int(verse["surah"])
        entry = surahs.setdefault(
            number,
            {
                "number": number,
                "arabic": verse["surah_name"],
                "english": verse["surah_name_en"],
                "ayahs": 0,
                "juz": juz_of_first_ayah.get(number, 1),
            },
        )
        entry["ayahs"] += 1

    if len(surahs) != 114:
        raise SystemExit(f"Expected 114 surahs in the corpus, found {len(surahs)}")
    return [surahs[n] for n in sorted(surahs)]


def escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    surahs = load_surahs()
    lines = [
        "// <auto-generated>",
        "//     Generated by tools/build_surah_catalog.py from the bundled Quran",
        "//     corpus. Do not edit by hand: run the generator instead so the API",
        "//     and the app never disagree about surah metadata.",
        "// </auto-generated>",
        "",
        "namespace Tilawa.Api.Data;",
        "",
        "/// <summary>",
        "/// Static metadata for all 114 surahs, shared by every user.",
        "/// </summary>",
        "public static class SurahCatalog",
        "{",
        "    public readonly record struct Entry(",
        "        int Number,",
        "        string EnglishName,",
        "        string ArabicName,",
        "        string JuzLabel,",
        "        int AyahCount);",
        "",
        "    public static readonly IReadOnlyList<Entry> All =",
        "    [",
    ]

    for surah in surahs:
        juz = surah["juz"]
        label = NAMED_JUZ.get(juz, f"Juz {juz}")
        lines.append(
            f'        new({surah["number"]}, "{escape(surah["english"])}", '
            f'"{escape(surah["arabic"])}", "{escape(label)}", {surah["ayahs"]}),'
        )

    lines += [
        "    ];",
        "}",
        "",
    ]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    # UTF-8 with BOM: Roslyn falls back to the system codepage for BOM-less
    # source files, which would mangle the Arabic names on Windows.
    OUTPUT.write_text("\n".join(lines), encoding="utf-8-sig")
    print(f"Wrote {OUTPUT} ({len(surahs)} surahs)")


if __name__ == "__main__":
    main()
